name: Lead Application
description: I would like to be one  of the lead of this awesome community
title: " Lead Application"
labels: [ Lead Application]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Why should you be a lead ?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](https://discord.gg/tc7ZMtzy3K)
        Feel free to check out other cool repositories of the GeeksCommunity [here](https://github.com/GeeksCommunity)
